export const SCREENS = {
  LOGIN: "login",
  REGISTER: "register",
  VERIFY_ACCOUNT: "verify-account",
  WELCOME: "welcome",
  PROFILE: "profile",
  EDIT_PROFILE: "edit-profile",
  CHANGE_PASSWORD: "change-password",
  ABOUT_APP: "about-app",
  AQUARIUM: "aquarium",
  DETAIL: "detail",
  CALIBRATION: "calibration",
  METRIC_DETAIL: "metric-detail",
  EDIT_AQUARIUM: "edit-aquarium",
};
