name: Deploy Node Application 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image for Backend
        run: |
          cd server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/aquarium-server:latest .
      - name: Publish Image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/aquarium-server:latest
      - name: Build Client Image
        run: |
          cd client
          docker build -t ${{ secrets.DOCKER_USERNAME }}/aquarium-client:latest \
            --build-arg VITE_BACKEND_URL='${{ secrets.VITE_BACKEND_URL }}' .
      - name: Push Client to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/aquarium-client:latest

      - name: Stoping containers
        run: |
          docker rm -f aquarium-server || true
          docker rm -f aquarium-client || true

      - name: Start Server container
        run: |
          docker run -d -p 3001:3001 --name aquarium-server \
            -e DATABASE_URL='${{ secrets.DATABASE_URL }}' \
            -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            ${{ secrets.DOCKER_USERNAME }}/aquarium-server:latest

      - name: Start Prisma migrating
        run: |
          docker exec aquarium-server npx prisma migrate deploy

      - name: starting client container
        run: |
          docker run -d -p 80:80 --name aquarium-client \
            ${{ secrets.DOCKER_USERNAME }}/aquarium-client:latest
      